#!/usr/bin/env python3
"""Rebuild the Windows application icon from the macOS 1024px master.

`windows/runner/resources/app_icon.ico` is what Explorer, the taskbar and the
title bar draw: `windows/runner/Runner.rc` binds it to `IDI_APP_ICON`, which
`windows/runner/resource.h` gives the lowest resource id so the shell keys the
.exe icon to it, and `win32_window.cpp` loads it for the window class. There is
no build step behind that file, so the shipped artwork is whatever is committed
and it has to be regenerated by hand when the mark changes:

    python3 tool/make-windows-icon.py

Stdlib only, plus `sips`, which ships with macOS. ImageMagick and Pillow are not
present on a stock Mac and a checked-in asset is not worth a toolchain: `sips`
does the resampling, this file does the ICO container.

Apple's master is drawn to the macOS icon grid — the mark occupies a centred
square inside a larger canvas, with the surrounding inset left transparent for
the shadow the system composites. Windows applies neither a mask nor a shadow
and draws icons full-bleed, so that inset is measured off the master and cropped
away before anything is resampled.
"""

from __future__ import annotations

import struct
import subprocess
import tempfile
import zlib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_1024.png"
OUTPUT = REPO / "windows/runner/resources/app_icon.ico"

# 16/20/24 are the title bar and Explorer at 100/125/150% DPI, 32/40/48 the
# taskbar and alt-tab at those same scales, 64/128/256 Explorer's larger views
# and the high-DPI shell. Windows down-samples the nearest larger entry when one
# is missing, which is what makes an icon look soft at exactly one zoom level.
SIZES = (16, 20, 24, 32, 40, 48, 64, 128, 256)

# Vista and later read a PNG-compressed entry, and only 256 is worth it: as a
# raw DIB that one entry is 256*256*4 bytes of bitmap alone, more than ten times
# the rest of the file put together.
PNG_ENTRY = 256

# Alpha above this counts as the mark rather than its drop shadow. The shadow
# fades out over ~30px, so any threshold in the middle of the range finds the
# same edge; 128 is simply the middle.
OPAQUE = 128


def decode_png(path: Path) -> tuple[int, int, bytes]:
    """Decode an 8-bit non-interlaced PNG to straight RGBA rows, top-down.

    Only the shapes `sips` emits are handled — anything else raises rather than
    quietly producing a wrong icon.
    """
    data = path.read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise SystemExit(f"{path} is not a PNG")

    position, compressed = 8, b""
    width = height = depth = color_type = interlace = None
    while position < len(data):
        length, kind = struct.unpack(">I4s", data[position : position + 8])
        position += 8
        chunk = data[position : position + length]
        position += length + 4  # skip the trailing CRC
        if kind == b"IHDR":
            width, height, depth, color_type, _, _, interlace = struct.unpack(
                ">IIBBBBB", chunk
            )
        elif kind == b"IDAT":
            compressed += chunk
        elif kind == b"IEND":
            break
    if depth != 8 or color_type not in (2, 6) or interlace != 0:
        raise SystemExit(f"{path}: expected 8-bit non-interlaced RGB/RGBA")

    channels = 4 if color_type == 6 else 3
    raw = zlib.decompress(compressed)
    stride = width * channels
    out = bytearray(width * height * 4)
    previous = bytearray(stride)
    read = 0
    for y in range(height):
        # Every PNG scanline is prefixed with the filter it was encoded under
        # and has to be reversed against the reconstructed row above it.
        filter_type = raw[read]
        read += 1
        line = bytearray(raw[read : read + stride])
        read += stride
        if filter_type == 1:  # Sub
            for i in range(channels, stride):
                line[i] = (line[i] + line[i - channels]) & 255
        elif filter_type == 2:  # Up
            for i in range(stride):
                line[i] = (line[i] + previous[i]) & 255
        elif filter_type == 3:  # Average
            for i in range(stride):
                left = line[i - channels] if i >= channels else 0
                line[i] = (line[i] + ((left + previous[i]) >> 1)) & 255
        elif filter_type == 4:  # Paeth
            for i in range(stride):
                left = line[i - channels] if i >= channels else 0
                up = previous[i]
                upper_left = previous[i - channels] if i >= channels else 0
                pa = abs(up - upper_left)
                pb = abs(left - upper_left)
                pc = abs(left + up - 2 * upper_left)
                if pa <= pb and pa <= pc:
                    predictor = left
                elif pb <= pc:
                    predictor = up
                else:
                    predictor = upper_left
                line[i] = (line[i] + predictor) & 255
        offset = y * width * 4
        if channels == 4:
            out[offset : offset + stride] = line
        else:
            for x in range(width):
                out[offset + 4 * x : offset + 4 * x + 3] = line[3 * x : 3 * x + 3]
                out[offset + 4 * x + 3] = 255
        previous = line
    return width, height, bytes(out)


def opaque_side(width: int, height: int, rgba: bytes) -> int:
    """The side of the centred opaque square inside the macOS master.

    Measured rather than hard-coded: the inset is a property of the artwork, and
    a new master drawn to a different grid should crop correctly instead of
    silently shipping padding or a clipped mark.
    """
    left, top, right, bottom = width, height, -1, -1
    for y in range(height):
        row = y * width * 4
        for x in range(width):
            if rgba[row + 4 * x + 3] > OPAQUE:
                left = min(left, x)
                right = max(right, x)
                top = min(top, y)
                bottom = max(bottom, y)
    if right < 0:
        raise SystemExit(f"{SOURCE}: no opaque pixels")

    side = right - left + 1
    # `sips -c` crops to the centre, which is the only crop it offers. Apple's
    # grid centres the shape, so that is enough — but if a future master is off
    # centre or not square, say so instead of cropping the mark in half.
    if bottom - top + 1 != side:
        raise SystemExit(f"{SOURCE}: opaque bounds are not square")
    if left + right != width - 1 or top + bottom != height - 1:
        raise SystemExit(f"{SOURCE}: opaque bounds are not centred")
    return side


def dib_entry(width: int, height: int, rgba: bytes) -> bytes:
    """A 32-bpp BGRA icon image: BITMAPINFOHEADER, XOR bitmap, AND mask.

    The header declares twice the real height because the format counts the
    1-bpp AND mask as part of the bitmap. That mask is redundant for a 32-bpp
    entry, but the structure is not optional and Windows still reads it.
    """
    header = struct.pack(
        "<IiiHHIIiiII",
        40,  # biSize
        width,
        height * 2,  # biHeight: colour bitmap plus AND mask
        1,  # biPlanes
        32,  # biBitCount
        0,  # biCompression: BI_RGB
        width * height * 4,  # biSizeImage
        0,
        0,
        0,
        0,
    )
    xor = bytearray(width * height * 4)
    mask_stride = ((width + 31) // 32) * 4  # AND mask rows are 4-byte aligned
    mask = bytearray(mask_stride * height)
    for y in range(height):
        source = (height - 1 - y) * width * 4  # DIB rows run bottom-up
        target = y * width * 4
        mask_row = y * mask_stride
        for x in range(width):
            red, green, blue, alpha = rgba[source + 4 * x : source + 4 * x + 4]
            xor[target + 4 * x : target + 4 * x + 4] = bytes(
                (blue, green, red, alpha)
            )
            if alpha == 0:
                mask[mask_row + (x >> 3)] |= 0x80 >> (x & 7)
    return header + bytes(xor) + bytes(mask)


def sips(*args: str) -> None:
    subprocess.run(["sips", *args], check=True, capture_output=True)


def main() -> None:
    width, height, rgba = decode_png(SOURCE)
    side = opaque_side(width, height, rgba)

    with tempfile.TemporaryDirectory() as directory:
        temporary = Path(directory)
        full_bleed = temporary / "full_bleed.png"
        sips("-c", str(side), str(side), str(SOURCE), "--out", str(full_bleed))

        images: list[tuple[int, bytes]] = []
        for size in SIZES:
            scaled = temporary / f"{size}.png"
            sips("-z", str(size), str(size), str(full_bleed), "--out", str(scaled))
            if size == PNG_ENTRY:
                images.append((size, scaled.read_bytes()))
            else:
                images.append((size, dib_entry(*decode_png(scaled))))

    # ICONDIR: reserved, type 1 (icon), count. Then one 16-byte ICONDIRENTRY per
    # image, then the images themselves in the same order.
    directory_block = struct.pack("<HHH", 0, 1, len(images))
    offset = 6 + 16 * len(images)
    body = b""
    for size, image in images:
        directory_block += struct.pack(
            "<BBBBHHII",
            0 if size >= 256 else size,  # 256 does not fit a byte; 0 means 256
            0 if size >= 256 else size,
            0,  # bColorCount: 0 for a true-colour entry
            0,  # bReserved
            1,  # wPlanes
            32,  # wBitCount
            len(image),
            offset,
        )
        offset += len(image)
        body += image

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_bytes(directory_block + body)
    print(
        f"wrote {OUTPUT.relative_to(REPO)}: "
        f"{len(images)} entries from a {side}x{side} crop, "
        f"{OUTPUT.stat().st_size} bytes"
    )


if __name__ == "__main__":
    main()
